version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS:Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:622711946516:task-definition/DemoAppTaskDefinition:1"
        LoadBalancerInfo:
          ContainerName: "DemoAppContainer"
          ContainerPort: 8000