# Generated by Django 6.0.1 on 2026-01-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='Default.png', null=True, upload_to=''),
        ),
    ]
